grid:
  title: Stable Diffusion model validation framework for image generation v1.1
  description: A framework for structuring the validation of image-generated AI models, in an attempt to mechanize the validation of AI-generated models and make them easily reproducible.
  format: png
  author: Kairin @ https://github.com/kai-rin
  params:
    steps: 20
    CFG Scale: 7
    Width: 512
    Height: 768
axes:
  Sampler: DPM++ 2M Karras, DPM++ SDE Karras
  Seed: 1234, 5678, 9012
  Prompt: 1girl, || absurdres, highres, ultra detailed, (1girl:1.3), || ((masterpiece:1.4, best quality)),((masterpiece, best quality)),(photo realistic:1.4),1girl,
  Negative Prompt: EasyNegative, nsfw, || EasyNegative, (worst quality, low quality:1.4), underwear, nsfw, || (worst quality:2, low quality, panties, nipples, nsfw:2), (zombie, sketch, interlocked fingers, comic), || EasyNegativeV2, nsfw,
  Clip Skip: 1, 2
