grid:
  title: Checkpoint Testing Framework Grid for Quick Survey
  description: a matrix-based approach to organize and visualize the results of testing activities at a specific checkpoint. This procedure is designed to facilitate a rapid assessment of the checkpoint specification, helping promptographer identify the characteristics in a timely manner.
  format: png
  author: Kairin
axes:
  Sampler: DPM++ 2M Karras, DPM++ SDE Karras
  Seed: 1234, 5678, 9012
  Prompt: 1girl, || absurdres, highres, ultra detailed, (1girl:1.3), || ((masterpiece:1.4, best quality)),((masterpiece, best quality)),(photo realistic:1.4),1girl,
  Negative Prompt: EasyNegative, nsfw, || EasyNegativeV2, nsfw, || EasyNegative, (worst quality, low quality:1.4), nsfw, || (worst quality:2, low quality:2), (zombie, sketch, interlocked fingers, comic), nsfw,
  Clip Skip: 1, 2
